# TODO: Add coverage and benchmarking

name: Test CLI 

on:
  # push:
  #   branches: ["main", "stable"]
  #   paths:
  #     - '.github/workflows/cli.yaml'
  #     - 'cli/**'
  pull_request:
    branches: ["main", "stable"]
    paths:
      - '.github/workflows/cli.yaml'
      - 'cli/**'

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli/
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.2
        with:
          deno-version: 2.2.0

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint
  test:
    runs-on: ubuntu-latest
    needs: analyze
    defaults:
      run:
        working-directory: cli/
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.2
        with:
          deno-version: 2.2.0

      - name: Run tests
        run: deno test -A
