# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Analyze and Test Deno Workspace 

on:
  # push:
  #   branches: ["main", "stable"]
  # pull_request:
  #   branches: ["main", "stable"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.2
        with:
          # The Deno version to install. Can be a semver version of a stable release, "canary" for the latest canary, or the Git hash of a specific canary release.
          deno-version: 2.2.0
          # # File containing the Deno version to install, such as .dvmrc or .tool-versions.
          # deno-version-file: # optional
          # # The name to use for the binary.
          # deno-binary-name: # optional, default is deno
          

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
